### ISSUE TITLE
Math domain error

### ISSUE THREAD

**Issue by yhoogstrate** [yhoogstrate/dr-disco#80]
```
[DetectOutput.py:203 - classify()] 2017-10-02 13:44:53,089 - INFO - Loading protocol/drdisco_results/dr-d
isco_v0.12.1/filtered/xx18017x.full.txt[only_valid=false]
Traceback (most recent call last):
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/bin/dr-disco", line 5, in <module>
    pkg_resources.run_script('dr-disco==0.12.1', 'dr-disco')
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/pkg_r
esources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/pkg_r
esources.py", line 1361, in run_script
    exec(script_code, namespace, namespace)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/dr_di
sco-0.12.1-py2.7.egg/EGG-INFO/scripts/dr-disco", line 151, in <module>

  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/dr_di
sco-0.12.1-py2.7.egg/EGG-INFO/scripts/dr-disco", line 48, in main

  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/click
-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/click
-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/click
-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/click
-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/click
-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data/users/youri/ProToCol/drdisco_analysis/drdisco/.venv/local/lib/python2.7/site-packages/dr_di
sco-0.12.1-py2.7.egg/EGG-INFO/scripts/dr-disco", line 135, in CLI_classify

  File "build/bdist.linux-x86_64/egg/drdisco/DetectOutput.py", line 283, in classify
ValueError: math domain error
[Classify.py:88 - add_junctions_from_file()] 2017-10-02 13:44:57,276
```

e.alignmentscore is somehow set to: 0 -2147483518

**Comment by yhoogstrate** [comment]
This is due to a bug in STAR as this was found in the alignment:

```
read_uid:x:xxxx:xxxxx:65019	385	chr8	43129071	3	60M15S	chr13	95279898	0	TGACATCTTCCCACTATTAAGTCTTCCAGTACATGAACACATGCATTTTCCTGATGACTATCTCAGCATTGTCGG	C@@FFFFFHHHHGJIJJJIIJIIICHIHJHHGHGGHIJIGE@HCHIJ>DHHCAFF@DBGI?FGJBFGGHHH;=5;	NH:i:2	HI:i:2	AS:i:59	nM:i:0	NM:i:0	FI:i:1	RG:Z:spanning_paired_2	SA:Z:chr13,95279953,60S15M,3,+,0;chr13,95279897,56M19S,3,-,0	LB:Z:read_uid:x:xxxx:xxxxx.65019
read_uid:x:xxxx:xxxxx:65019	83	chr13	95279898	3	56M19S	=	95279954	0	CTGGGACCACCACCCTGGAAGGACACTTGAGCCCTACTCAAGGACCCACCACAACAATCCCCATTGGAAAACAAG	CCB@6';?4A;)JIHFIGIJIHEGBIGGGFHGCEHGHFBIGGB:>HGFIGGGHEFAGHIFJIHHFHFDFEFD@C@	NH:i:2	HI:i:1	AS:i:-2147483577	nM:i:0	NM:i:0	RG:Z:silent_mate	SA:Z:chr13,95279953,60S15M,3,+,0;chr8,43129070,60M15S,3,+,0	read_uid:x:xxxx:xxxxx:65019
read_uid:x:xxxx:xxxxx:65019	163	chr13	95279954	3	60S15M	chr8	43129071	0	TGACATCTTCCCACTATTAAGTCTTCCAGTACATGAACACATGCATTTTCCTGATGACTATCTCAGCATTGTCGG	C@@FFFFFHHHHGJIJJJIIJIIICHIHJHHGHGGHIJIGE@HCHIJ>DHHCAFF@DBGI?FGJBFGGHHH;=5;	NH:i:2	HI:i:1	AS:i:-2147483577	nM:i:0	NM:i:0	FI:i:0	RG:Z:spanning_paired_1	SA:Z:chr8,43129070,60M15S,3,+,0;chr13,95279897,56M19S,3,-,0	LB:Z:read_uid:x:xxxx:xxxxx.65019
(.venv)-----
```
